### ISSUE TITLE
请教一下：这个固件在newifi3-d2上5G信号稳定吗？

### ISSUE THREAD

**Issue by luffythink** [zyhibook/newifi3-d2-openwrt#1]
因为看到有说openwrt固件无线传输不是很稳定，不知道这个版本怎么样，希望得到回复，谢谢。已star持续关注。

**Comment by zyhibook** [comment]
![](https://www.imglink.cc/images/2021/01/17/ee7e640eed52b758c80ff31021b23817.png)
我用着没啥问题，一般我是用5G的那个无线，200M宽度能跑满，刷b站也不会断流，使用来说很不错
